Specialty.find_or_create_by(name:'Acupuncturist')
Specialty.find_or_create_by(name:'Allergist (Immunologist)')
Specialty.find_or_create_by(name:'Audiologist')
Specialty.find_or_create_by(name:'Cardiologist (Heart Doctor)')
Specialty.find_or_create_by(name:'Cardiothoracic Surgeon')
Specialty.find_or_create_by(name:'Chiropractor')
Specialty.find_or_create_by(name:'Dentist')
Specialty.find_or_create_by(name:'Dermatologist')
Specialty.find_or_create_by(name:'Dietitian / Nutritionist')
Specialty.find_or_create_by(name:'Ear, Nose & Throat Doctor (ENT)')
Specialty.find_or_create_by(name:'Endocrinologist (incl Diabetes Specialists)')
Specialty.find_or_create_by(name:'Eye Doctor')
Specialty.find_or_create_by(name:'Gastroenterologist')
Specialty.find_or_create_by(name:'Hearing Specialist')
Specialty.find_or_create_by(name:'Hematologist (Blood Specialist)')
Specialty.find_or_create_by(name:'Infectious Disease Specialist')
Specialty.find_or_create_by(name:'Infertility Specialist')
Specialty.find_or_create_by(name:'Midwife')
Specialty.find_or_create_by(name:'Naturopathic Doctor')
Specialty.find_or_create_by(name:'Nephrologist (Kidney Specialist)')
Specialty.find_or_create_by(name:'Neurologist (incl Headache Specialists)')
Specialty.find_or_create_by(name:'Neurosurgeon')
Specialty.find_or_create_by(name:'OB-GYN (Obstetrician-Gynecologist)')
Specialty.find_or_create_by(name:'Oncologist')
Specialty.find_or_create_by(name:'Ophthalmologist')
Specialty.find_or_create_by(name:'Optometrist')
Specialty.find_or_create_by(name:'Orthodontist')
Specialty.find_or_create_by(name:'Orthopedic Surgeon (Orthopedist)')
Specialty.find_or_create_by(name:'Pain Management Specialist')
Specialty.find_or_create_by(name:'Pediatric Dentist')
Specialty.find_or_create_by(name:'Pediatrician')
Specialty.find_or_create_by(name:'Physiatrist (Physical Medicine)')
Specialty.find_or_create_by(name:'Physical Therapist')
Specialty.find_or_create_by(name:'Plastic Surgeon')
Specialty.find_or_create_by(name:'Podiatrist (Foot and Ankle Specialist)')
Specialty.find_or_create_by(name:'Primary Care Doctor')
Specialty.find_or_create_by(name:'Prosthodontist')
Specialty.find_or_create_by(name:'Psychiatrist')
Specialty.find_or_create_by(name:'Psychologist')
Specialty.find_or_create_by(name:'Pulmonologist (Lung Doctor)')
Specialty.find_or_create_by(name:'Radiologist')
Specialty.find_or_create_by(name:'Rheumatologist')
Specialty.find_or_create_by(name:'Sleep Medicine Specialist')
Specialty.find_or_create_by(name:'Sports Medicine Specialist')
Specialty.find_or_create_by(name:'Surgeon')
Specialty.find_or_create_by(name:'Therapist / Counselor')
Specialty.find_or_create_by(name:'Urgent Care Doctor')
Specialty.find_or_create_by(name:'Urological Surgeon')
Specialty.find_or_create_by(name:'Urologist')
Specialty.find_or_create_by(name:'Vascular Surgeon')
