default: &default
  adapter: mysql2
  host: localhost
  username: outpatient
  password: ENV["DATABASE_PASSWORD"]
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: outpatient_dev

test:
  <<: *default
  database: outpatient_test

production:
  <<: *default
  database: outpatient_dev
