default: &default
  adapter: postgresql
  host: localhost
  username: chatmd
  password: ENV["DATABASE_PASSWORD"]
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: chatmd_dev

test:
  <<: *default
  database: chatmd_test

production:
  <<: *default
  database: chatmd_dev
