# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1860d656f0881915e5c47cdb180da184f0aacf7ce84114071628422921a3e6da0820ea5d2460f08d1cd1a2aff4d2351997054b66f3d6e05bae66602cdddec194

test:
  secret_key_base: 78cb9cbda660650c02af2b954f7077f4eaea83018baa40a2a2daa673011c94a3414628d741f2b4fb758c220bd288e8803eefa9376f53523af033800e4c177f09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
